### ISSUE TITLE
Lsftp not working on windows 11

### ISSUE THREAD

**Issue by archwizmgm** [blacknon/lssh#146]
Here is the log.
```bash
Start lsftp...
Select Server :ServerName1
lsftp>> ls
panic: exec: "stty": executable file not found in %PATH%
        panic: close of closed channel

goroutine 1 [running]:
github.com/mattn/go-tty.(*TTY).close(0xc000197220)
        D:/a/lssh/lssh/vendor/github.com/mattn/go-tty/tty_windows.go:331 +0x90
github.com/mattn/go-tty.(*TTY).Close(...)
        D:/a/lssh/lssh/vendor/github.com/mattn/go-tty/tty.go:38
github.com/c-bata/go-prompt.(*WindowsParser).TearDown(0xc0000971ef?)
        D:/a/lssh/lssh/vendor/github.com/c-bata/go-prompt/input_windows.go:37 +0x16
github.com/c-bata/go-prompt.(*Prompt).tearDown(0xc0001dc090)
        D:/a/lssh/lssh/vendor/github.com/c-bata/go-prompt/prompt.go:293 +0x2c
panic({0x7ff6b6332680?, 0xc000216a00?})
        C:/hostedtoolcache/windows/go/1.22.7/x64/src/runtime/panic.go:770 +0x132
github.com/blacknon/textcol.check(...)
        D:/a/lssh/lssh/vendor/github.com/blacknon/textcol/textcol.go:119
github.com/blacknon/textcol.getTermWidth()
        D:/a/lssh/lssh/vendor/github.com/blacknon/textcol/textcol.go:84 +0x118
github.com/blacknon/textcol.PrintColumns(0xc0000975b0, 0x2)
        D:/a/lssh/lssh/vendor/github.com/blacknon/textcol/textcol.go:34 +0x178
github.com/blacknon/lssh/sftp.(*RunSftp).executeRemoteLs(0xc0002c6488, 0xc0002969a0, 0xc000097ac8)
        D:/a/lssh/lssh/sftp/cmd_ls.go:291 +0x3b1
github.com/blacknon/lssh/sftp.(*RunSftp).ls.func1(0xc0002969a0)
        D:/a/lssh/lssh/sftp/cmd_ls.go:86 +0x22b
github.com/urfave/cli.HandleAction({0x7ff6b6311720?, 0xc00028ca50?}, 0xc0000dc510?)
        D:/a/lssh/lssh/vendor/github.com/urfave/cli/app.go:514 +0x50
github.com/urfave/cli.(*App).Run(0xc000059c00, {0xc00028caf0, 0x1, 0x1})
        D:/a/lssh/lssh/vendor/github.com/urfave/cli/app.go:274 +0x806
github.com/blacknon/lssh/sftp.(*RunSftp).ls(0xc0002c6488, {0xc00028ca40, 0x1, 0x1})
        D:/a/lssh/lssh/sftp/cmd_ls.go:93 +0x798
github.com/blacknon/lssh/sftp.(*RunSftp).Executor(0xc0002c6488, {0xc0002853d4?, 0xc000197220?})
        D:/a/lssh/lssh/sftp/shell.go:130 +0x13d
github.com/c-bata/go-prompt.(*Prompt).Run(0xc0001dc090)
        D:/a/lssh/lssh/vendor/github.com/c-bata/go-prompt/prompt.go:84 +0x73f
github.com/blacknon/lssh/sftp.(*RunSftp).shell(0xc0002c6488)
        D:/a/lssh/lssh/sftp/shell.go:78 +0x60a
github.com/blacknon/lssh/sftp.(*RunSftp).Start(0xc0002c6488)
        D:/a/lssh/lssh/sftp/main.go:117 +0x20f
main.Lsftp.func1(0xc0000f4000)
        D:/a/lssh/lssh/cmd/lsftp/args.go:107 +0x47b
github.com/urfave/cli.HandleAction({0x7ff6b6311720?, 0x7ff6b63d95b8?}, 0xc00003a5c0?)
        D:/a/lssh/lssh/vendor/github.com/urfave/cli/app.go:514 +0x50
github.com/urfave/cli.(*App).Run(0xc000059340, {0xc000030410, 0x1, 0x1})
        D:/a/lssh/lssh/vendor/github.com/urfave/cli/app.go:274 +0x806
main.main()
        D:/a/lssh/lssh/cmd/lsftp/main.go:16 +0x65
```

**Comment by blacknon** [comment]
Oh, thanks.
Looking at the log, it seems that the cause is probably that stty does not exist in the Windows environment.
I don't have a Windows environment at hand right now, so I'll prepare one and try to deal with it.
